# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
# jobs:
#   build-and-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: npm install
#             - run: npm test
# workflows:
#     build-and-test:
#       jobs:
#         - build-and-test

version: 2
jobs:
  build: 
    docker: 
      # specify the version you desire here
      - image: circleci/node:12.18.1
    
    steps: 
      - checkout
      - run: npm install
      - run: npm test
